language: python
dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
python: 3.7
cache: pip
install: pip install flake8 pytest --editable .
before_script:
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics
    # exit-zero treates all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
    pytest --capture=sys
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
